name: CI MLflow Training

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy matplotlib dagshub

      - name: Train Model
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_REPO: ${{ secrets.DAGSHUB_REPO }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/${{ secrets.DAGSHUB_REPO }}.mlflow
        run: |
          unset MLFLOW_RUN_ID
          mlflow run MLProject --env-manager=local

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            feature_importance.png
            actual_vs_predicted.png